"project_id_env": "projectId"
"api_token_env": "personal-access-token"
"preserve_hierarchy": true
"base_url": "https://andriy.crowdin.com"

"files": [
  {
    "source": "/en/en.json",                                       #source files filter
    "translation": "/%two_letters_code%/%two_letters_code%.json"        #where translations are stored
  }
]
